---
- name: Manage windows servers
  hosts: win
  tasks:

  - name: add directory for Nginx
    win_file:
      path: C:\nginx
      state: directory

  - name: Download Nginx
    win_get_url:
      url: https://nginx.org/download/nginx-1.20.1.zip # Update URL to the latest version
      dest: C:\nginx\nginx.zip
      force: true

  - name: Unzip Nginx
    win_unzip:
      src: C:\nginx\nginx.zip
      dest: C:\nginx
      creates: C:\nginx\nginx-1.20.1

  - name: Start Nginx
    win_shell: Start-Process -NoNewWindow -FilePath "C:\nginx\nginx-1.20.1\nginx.exe"
